Repository trevorskaggs/shelterly, pull requests merged in 2021-01, with the labels that each got.

#170 Add SR map to Hotline page.
  frontend/src/hotline/Hotline.js
  hotline/views.py
Labels: Good to Merge

#179 Owner drivers license
  frontend/src/hotline/HotlineForms.js
  frontend/src/people/PeopleForms.js
  hotline/migrations/0012_auto_20210101_1101.py
  hotline/models.py
Labels: Good to Merge

#174 Renamed Best Contact to Comments and fixed First Responder Calling typo
  frontend/src/hotline/Hotline.js
  frontend/src/people/PeopleForms.js
  frontend/src/people/PeopleViews.js
  people/migrations/0011_auto_20201229_1155.py
  people/models.py
Labels: Good to Merge

#175 Add functionality to create N copies of an animal.
  animals/views.py
  frontend/src/animals/AnimalForms.js
  frontend/src/components/Form.js
  frontend/src/hotline/HotlineViews.js
Labels: ready for review

#173 Make details links from searches open in a new tab.
  evac/views.py
  frontend/src/animals/AnimalTables.js
  frontend/src/evac/Evac.js
  frontend/src/evac/EvacTables.js
  frontend/src/hotline/Hotline.js
  frontend/src/hotline/Hotline.test.js
  frontend/src/hotline/HotlineTables.js
  frontend/src/people/PeopleTables.js
  frontend/src/router.js
  hotline/views.py
Labels: ready for review

#187 Add previous visit note to DA search and summary.
  frontend/src/evac/EvacTables.js
  frontend/src/evac/EvacViews.js
  frontend/src/shelter/Shelter.js
Labels: Good to Merge

#156 Backend performance optimizations
  animals/serializers.py
  animals/views.py
  evac/serializers.py
  evac/tests.py
  evac/views.py
  frontend/src/accounts/AccountsForms.js
  frontend/src/accounts/AccountsReducer.js
  frontend/src/accounts/AccountsUtils.js
  hotline/serializers.py
  hotline/views.py
  people/serializers.py
  people/views.py
  settings.py
  shelter/serializers.py
Labels: ready for review

#188 Fix map performance at scale
  frontend/src/evac/EvacViews.js
Labels: bug, critical, ready for review

#148 Update Tab Name and Favicon
  frontend/public/favicon.ico
  frontend/src/components/Sidebar.js
Labels: ready for review

#190 Fix Django/React Router Issue
  urls.py
Labels: ready for review

#195 Add Unknown animal size.
  animals/choices.py
  animals/serializers.py
  frontend/src/animals/AnimalForms.js
  frontend/src/animals/constants.js
  frontend/src/people/PeopleForms.js
Labels: Good to Merge

#194 Enhance phone regex and clean phone field data.
  frontend/src/people/PeopleForms.js
  people/views.py
Labels: Good to Merge

#177 Add workflow stepper to Hotline SR creation
  frontend/package-lock.json
  frontend/src/animals/AnimalForms.js
  frontend/src/animals/AnimalTables.js
  frontend/src/animals/AnimalViews.js
  frontend/src/animals/Animals.js
  frontend/src/animals/Animals.test.js
  frontend/src/evac/EvacForms.js
  frontend/src/evac/EvacViews.js
  frontend/src/hotline/Hotline.js
  frontend/src/hotline/HotlineForms.js
  frontend/src/hotline/HotlineTables.js
  frontend/src/hotline/HotlineViews.js
  frontend/src/hotline/HotlineWorkflow.js
  frontend/src/people/People.js
  frontend/src/people/PeopleForms.js
  frontend/src/people/PeopleViews.js
  frontend/src/router.js
  frontend/src/shelter/Shelter.js
  frontend/src/shelter/ShelterDetails.js
Labels: Good to Merge

#193 Display first responder agency
  frontend/src/hotline/HotlineTables.js
  frontend/src/hotline/HotlineViews.js
  frontend/src/people/PeopleTables.js
  frontend/src/people/PeopleViews.js
Labels: ready for review

#201 Add stepper to intake workflow.
  animals/migrations/0014_auto_20210113_1620.py
  animals/migrations/0015_auto_20210118_0541.py
  animals/models.py
  animals/serializers.py
  animals/views.py
  evac/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Shelterly.js
  frontend/src/animals/AnimalForms.js
  frontend/src/animals/AnimalViews.js
  frontend/src/animals/constants.js
  frontend/src/components/Sidebar.js
  frontend/src/evac/EvacForms.js
  frontend/src/evac/EvacViews.js
  frontend/src/hotline/Hotline.js
  frontend/src/hotline/HotlineWorkflow.js
  frontend/src/index.css
  frontend/src/intake/Intake.js
  frontend/src/people/PeopleForms.js
  frontend/src/router.js
  frontend/src/shelter/ShelterAssignment.js
  frontend/src/shelter/ShelterDetails.js
  people/serializers.py
  requirements.txt
  settings.py
  shelter/serializers.py
  shelter/views.py
Labels: enhancement, ready for review

#202 Fix manifest and static files issue
  .gitignore
  settings.py
  static/images/nvadg_logo.png
  urls.py
Labels: bug, critical, ready for review

#204 Update Django version in requirements.txt
  requirements.txt
Labels: ready for review

#208 Add reporter name to animal search query.
  animals/views.py
  frontend/src/animals/AnimalSearch.js
  frontend/src/animals/Animals.test.js
  frontend/src/router.js
Labels: ready for review

#223 Variety of misc small fixes.
  animals/choices.py
  animals/serializers.py
  animals/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/animals/AnimalForms.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/animals/AnimalViews.js
  frontend/src/animals/constants.js
  frontend/src/components/Form.js
  frontend/src/components/Header.js
  frontend/src/people/PeopleForms.js
  frontend/src/people/PeopleViews.js
  frontend/src/shelter/ShelterAssignment.js
  frontend/src/shelter/ShelterDetails.js
  frontend/src/shelter/ShelterForms.js
  shelter/migrations/0007_shelter_phone.py
  shelter/models.py
  shelter/serializers.py
  shelter/views.py
Labels: ready for review
