Repository trevorskaggs/shelterly, pull requests merged in 2021-04, with the labels that each got.

#278 Animal medical notes field
  animals/migrations/0018_animal_medical_notes.py
  animals/models.py
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalForm.js
  frontend/src/animals/AnimalSearch.js
Labels: Good to Merge

#275 Move view window to topmost error on page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/Form.js
  frontend/src/dispatch/Dispatch.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/hotline/Hotline.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/index.js
  frontend/src/people/PersonSearch.js
Labels: Good to Merge, bug

#272 Handle duplicate assigned SRs when deploying.
  animals/choices.py
  animals/serializers.py
  evac/views.py
  frontend/src/animals/AnimalForm.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/animals/constants.js
  frontend/src/components/AnimalCards.js
  frontend/src/components/Map.js
  frontend/src/components/Modals.js
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/hotline/ServiceRequestDispatchAssignment.js
  frontend/src/people/PersonForm.js
  frontend/src/shelter/ShelterRoomAssignment.js
  hotline/serializers.py
  hotline/views.py
  settings.py
Labels: bug, ready for review

#280 Add animal intake date.
  animals/migrations/0019_animal_intake_date.py
  animals/models.py
  animals/serializers.py
  animals/views.py
  evac/views.py
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalSearch.js
Labels: Good to Merge

#273 stepper-dark-theme - dark mode theme for stepper
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/StepperWorkflow.js
  frontend/src/index.css
Labels: Good to Merge

#281 Clean up ticket.
  animals/serializers.py
  animals/views.py
  evac/serializers.py
  evac/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Home.js
  frontend/src/Shelterly.js
  frontend/src/accounts/AccountsReducer.js
  frontend/src/accounts/AccountsUtils.js
  frontend/src/accounts/LoginForm.js
  frontend/src/accounts/PasswordReset.js
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalForm.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/AnimalCards.js
  frontend/src/components/AnimalRoomAssignmentCard.js
  frontend/src/components/Form.js
  frontend/src/components/Map.js
  frontend/src/components/Modals.js
  frontend/src/components/Sidebar.js
  frontend/src/dispatch/Dispatch.js
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/dispatch/DispatchTeamMemberForm.js
  frontend/src/dispatch/VisitNoteForm.js
  frontend/src/hotline/Hotline.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/hotline/ServiceRequestDispatchAssignment.js
  frontend/src/hotline/ServiceRequestForm.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/index.css
  frontend/src/people/OwnerContactForm.js
  frontend/src/people/PersonDetails.js
  frontend/src/people/PersonForm.js
  frontend/src/people/PersonSearch.js
  frontend/src/shelter/BuildingDetails.js
  frontend/src/shelter/BuildingForm.js
  frontend/src/shelter/RoomDetails.js
  frontend/src/shelter/RoomForm.js
  frontend/src/shelter/Shelter.js
  frontend/src/shelter/ShelterDetails.js
  frontend/src/shelter/ShelterForm.js
  frontend/src/shelter/ShelterRoomAssignment.js
  hotline/models.py
  hotline/serializers.py
  hotline/views.py
  location/utils.py
  settings.py
  shelter/serializers.py
  shelter/views.py
Labels: Good to Merge

#312 Animal GET query performance
  animals/serializers.py
  animals/views.py
  people/serializers.py
  shelter/models.py
  shelter/serializers.py
Labels: ready for review

#290 Use intermediate model AssignedRequest for DA/SR tracking.
  animals/migrations/0020_auto_20210420_1128.py
  animals/models.py
  animals/serializers.py
  animals/views.py
  evac/migrations/0011_auto_20210420_1128.py
  evac/migrations/0012_services_requests_through.py
  evac/migrations/0013_auto_20210420_1153.py
  evac/migrations/0014_auto_20210426_1146.py
  evac/models.py
  evac/serializers.py
  evac/views.py
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/AnimalRoomAssignmentCard.js
  frontend/src/components/Form.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/hotline/ServiceRequestDispatchAssignment.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/index.css
  frontend/src/shelter/ShelterRoomAssignment.js
  hotline/migrations/0016_auto_20210420_1128.py
  hotline/models.py
  hotline/serializers.py
  hotline/views.py
  people/migrations/0014_auto_20210420_1128.py
  people/migrations/0015_auto_20210426_1146.py
  people/models.py
  people/serializers.py
Labels: ready for review
