Repository trevorskaggs/shelterly, pull requests merged in 2021-03, with the labels that each got.

#245 Consolidate Intake functionality within Shelter section.
  frontend/src/animals/AnimalForm.js
  frontend/src/components/Sidebar.js
  frontend/src/components/StepperWorkflow.js
  frontend/src/intake/Intake.js
  frontend/src/router.js
  frontend/src/shelter/Shelter.js
  frontend/src/shelter/ShelterDetails.js
Labels: Good to Merge

#241 Address Lookup Improvements
  frontend/package-lock.json
  frontend/package.json
  frontend/src/animals/AnimalForm.js
  frontend/src/components/Form.js
  frontend/src/components/Map.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/dispatch/VisitNoteForm.js
  frontend/src/hotline/ServiceRequestDispatchAssignment.js
  frontend/src/hotline/ServiceRequestForm.js
  frontend/src/index.css
  frontend/src/people/PersonForm.js
  frontend/src/shelter/ShelterForm.js
Labels: ready for review

#243 Add Animal Index to Name
  animals/views.py
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/AnimalCards.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/index.css
  frontend/src/people/PersonDetails.js
  frontend/src/people/PersonSearch.js
  frontend/src/shelter/RoomDetails.js
  frontend/src/shelter/ShelterRoomAssignment.js
  hotline/views.py
  people/serializers.py
Labels: Good to Merge

#248 Support dispatch team names
  evac/admin.py
  evac/migrations/0009_auto_20210301_0732.py
  evac/migrations/0010_dispatchteam_name.py
  evac/models.py
  evac/serializers.py
  evac/urls.py
  evac/views.py
  frontend/src/dispatch/Dispatch.js
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/hotline/ServiceRequestSearch.js
  hotline/serializers.py
Labels: Good to Merge

#246 History pagination
  frontend/src/components/History.js
Labels: Good to Merge

#263 Scrollbar additions and improvements.
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/Scrollbars.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/index.css
  frontend/src/people/PersonSearch.js
  frontend/src/shelter/Shelter.js
  frontend/src/shelter/ShelterRoomAssignment.js
Labels: enhancement, ready for review

#262 Move LoginForm to be on Home page.
  frontend/src/Home.js
  frontend/src/accounts/AccountsReducer.js
  frontend/src/accounts/AccountsUtils.js
  frontend/src/router.js
Labels: Good to Merge

#259 Reunify all animals from SR and Owner pages.
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/people/PersonDetails.js
  hotline/models.py
  hotline/views.py
  people/views.py
Labels: Good to Merge, enhancement

#264 Dispatch Assignment Search Improvements
  evac/serializers.py
  evac/views.py
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/Map.js
  frontend/src/components/Scrollbars.js
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/hotline/Hotline.js
  frontend/src/hotline/ServiceRequestDispatchAssignment.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/index.css
  frontend/src/people/PersonSearch.js
Labels: ready for review

#270 Shelter pages improvements
  frontend/package-lock.json
  frontend/package.json
  frontend/src/animals/AnimalForm.js
  frontend/src/components/AnimalCards.js
  frontend/src/dispatch/DispatchTeamMemberForm.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/index.css
  frontend/src/people/PersonForm.js
  frontend/src/shelter/BuildingDetails.js
  frontend/src/shelter/BuildingForm.js
  frontend/src/shelter/RoomDetails.js
  frontend/src/shelter/Shelter.js
  frontend/src/shelter/ShelterDetails.js
  frontend/src/shelter/ShelterRoomAssignment.js
Labels: Good to Merge

#260 Reset Password functionality
  accounts/admin.py
  accounts/migrations/0003_auto_20210311_1031.py
  accounts/models.py
  accounts/serializers.py
  accounts/tests.py
  accounts/urls.py
  frontend/src/Shelterly.js
  frontend/src/accounts/Accounts.test.js
  frontend/src/accounts/LoginForm.js
  frontend/src/accounts/PasswordReset.js
  frontend/src/router.js
  requirements.txt
  settings.py
  templates/password_reset_email.html
  templates/password_reset_email.txt
  templates/registration_email.html
  templates/registration_email.txt
Labels: enhancement, ready for review
