Repository trevorskaggs/shelterly, pull requests merged in 2022-03, with the labels that each got.

#377 Recheck the user authentication status when user refocuses the window
  frontend/src/Home.js
  frontend/src/accounts/AccountsReducer.js
  frontend/src/accounts/AccountsUtils.js
  frontend/src/accounts/LoginForm.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/router.js
  settings.py
Labels: Good to Merge, Customer Request

#376 Improvements to the Kennel Card pages.
  animals/serializers.py
  animals/views.py
  frontend/src/animals/AnimalDetails.js
  templates/ui/animals/print.html
Labels: Good to Merge, ready for review, Customer Request

#378 Handle duplicate owners
  animals/views.py
  frontend/src/animals/AnimalForm.js
  frontend/src/components/StepperWorkflow.js
  frontend/src/hotline/ServiceRequestForm.js
  frontend/src/people/PersonDetails.js
  frontend/src/people/PersonForm.js
  hotline/views.py
  people/views.py
Labels: Good to Merge

#384 Better handling of active DAs when SRs/Animals are canceled.
  evac/views.py
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/hotline/ServiceRequestDetails.js
  hotline/models.py
  hotline/views.py
Labels: Good to Merge

#385 Fix image removal/upload logic
  animals/views.py
  frontend/src/animals/AnimalForm.js
Labels: Good to Merge
