Repository trevorskaggs/shelterly, pull requests merged in 2023-02, with the labels that each got.

#517 Add action endpoint to EvacAssignment viewset for geojson
  evac/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/dispatch/DispatchSummary.js
  urls.py
Labels: ready for review

#525 Add Use Existing Owner lookup to Person form.
  frontend/src/animals/AnimalForm.js
  frontend/src/hotline/ServiceRequestForm.js
  frontend/src/people/PersonForm.js
  frontend/src/people/PersonSearch.js
Labels: Good to Merge

#523 Shelter intake summary
  animals/migrations/0024_auto_20230201_1653.py
  animals/serializers.py
  animals/views.py
  evac/views.py
  frontend/src/Incident.js
  frontend/src/IncidentForm.js
  frontend/src/accounts/UserForm.js
  frontend/src/accounts/UserManagement.js
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalForm.js
  frontend/src/components/History.js
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/dispatch/DispatchTeamManagement.js
  frontend/src/dispatch/VisitNoteForm.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/hotline/ServiceRequestForm.js
  frontend/src/people/OwnerContactForm.js
  frontend/src/people/PersonDetails.js
  frontend/src/people/PersonForm.js
  frontend/src/router.js
  frontend/src/shelter/BuildingDetails.js
  frontend/src/shelter/BuildingForm.js
  frontend/src/shelter/RoomDetails.js
  frontend/src/shelter/RoomForm.js
  frontend/src/shelter/ShelterDetails.js
  frontend/src/shelter/ShelterForm.js
  frontend/src/shelter/ShelterIntake.js
  frontend/src/shelter/ShelterIntakeSummary.js
  frontend/src/shelter/ShelterRoomAssignment.js
  frontend/src/shelter/Utils.js
  hotline/serializers.py
  shelter/admin.py
  shelter/migrations/0015_intakesummary.py
  shelter/migrations/0016_auto_20230206_1422.py
  shelter/models.py
  shelter/serializers.py
  shelter/urls.py
  shelter/views.py
Labels: ready for review

#520 Adds print all buttons to all searchable pages
  frontend/src/animals/AnimalSearch.js
  frontend/src/animals/Utils.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/Utils.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useSubmitting.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/hotline/Utils.js
  frontend/src/people/PersonSearch.js
  frontend/src/people/Utils.js
  frontend/src/utils/pdf.js
Labels: Good to Merge, Customer Request

#536 0.69 bug fixes
  animals/views.py
  frontend/package.json
  frontend/src/animals/AnimalSearch.js
  frontend/src/dispatch/DispatchResolutionForm.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/people/PersonForm.js
  people/serializers.py
  people/views.py
Labels: ready for review
