Repository trevorskaggs/shelterly, pull requests merged in 2023-09, with the labels that each got.

#625 [#622] reuses a handy status label lookup object for proper capitalization
  frontend/src/hotline/Utils.js
  frontend/src/shelter/ShelterIntake.js
  frontend/src/utils/formatString.js
Labels: ready for review

#628 Add Organization model and data to owner liability forms.
  accounts/admin.py
  accounts/migrations/0008_auto_20230812_1516.py
  accounts/migrations/0009_default_org.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  frontend/src/constants.js
  frontend/src/hooks/useSubmitting.js
  frontend/src/people/PersonDetails.js
  frontend/src/people/PersonSearch.js
  frontend/src/people/Utils.js
  frontend/src/shelter/ShelterIntakeSummary.js
  frontend/src/shelter/Utils.js
Labels: Good to Merge

#643 Add export as CSV button to reports.
  frontend/src/reports/Reports.js
Labels: Customer Request
