Repository trevorskaggs/shelterly, pull requests merged in 2024-07, with the labels that each got.

#772 Improvements and fixes to the Animal and SR searches.
  animals/serializers.py
  animals/views.py
  evac/views.py
  frontend/src/Home.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/components/Form.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/hotline/ServiceRequestSearch.js
  frontend/src/people/PersonSearch.js
  frontend/src/reports/Reports.js
  hotline/serializers.py
  hotline/tests.py
  hotline/views.py
  people/views.py
Labels: ready for review

#779 762: adds colored risk indication to printable care schedule
  frontend/src/animals/Utils.js
  frontend/src/utils/pdf.js
Labels: ready for review

#778 774: Fix QR code link on animal care schedules
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalSearch.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/people/PersonDetails.js
  frontend/src/shelter/RoomDetails.js
  frontend/src/shelter/ShelterIntakeSummary.js
Labels: ready for review

#777 776: fixes animal link on MR to use `id_for_incident`
  frontend/src/vet/MedicalRecordDetails.js
Labels: ready for review

#782 fixes `id_for_incident` on patient component
  frontend/src/vet/components/Patient.js
Labels: ready for review

#783 775: fixed precision length (6) on address lookup lat/lon
  frontend/src/components/Form.js
Labels: ready for review

#792 Fix download all URLs on searches.
  frontend/src/animals/AnimalSearch.js
  frontend/src/hotline/ServiceRequestSearch.js
Labels: bug, ready for review

#799 Treatment quantity as a float and other vet fixes.
  evac/views.py
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/Utils.js
  frontend/src/vet/DiagnosisForm.js
  frontend/src/vet/ExamForm.js
  frontend/src/vet/MedicalRecordDetails.js
  frontend/src/vet/TreatmentPlanForm.js
  frontend/src/vet/Vet.js
  frontend/src/vet/VetRequestDetails.js
  frontend/src/vet/VetRequestSearch.js
  frontend/src/vet/VetStepperWorkflow.js
Labels: bug, ready for review

#800 Exclude canceled and reunited animals from vet tasks.
  frontend/src/vet/ExamForm.js
  frontend/src/vet/Vet.js
  vet/views.py
Labels: bug, ready for review

#803 Fix exam notes field validation.
  frontend/src/vet/ExamForm.js
  frontend/src/vet/MedicalRecordDetails.js
Labels: bug, ready for review

#804 Use simpler serializer for teams on deploy map.
  evac/serializers.py
  evac/views.py
  frontend/src/dispatch/DispatchMap.js
Labels: bug

#808 Better hide objects on Animal Search. Fix animal add owner.
  frontend/src/animals/AnimalSearch.js
  frontend/src/people/PersonForm.js
  people/views.py
Labels: bug, ready for review
