Repository trevorskaggs/shelterly, pull requests merged in 2024-08, with the labels that each got.

#805 More dispatch performance tweaks.
  evac/serializers.py
  evac/views.py
  frontend/src/components/Map.js
  frontend/src/dispatch/DispatchMap.js
  frontend/src/dispatch/DispatchSearch.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/hotline/ServiceRequestDispatchAssignment.js
  hotline/serializers.py
  hotline/views.py
Labels: bug, ready for review

#807 Issue #761: Animal notes and more on shelter intake form
  evac/views.py
  frontend/src/shelter/ShelterIntake.js
Labels: ready for review

#750 folds whitespace in printed DA
  frontend/src/dispatch/Utils.js
Labels: ready for review

#793 Add triage fields to animal shelter intake.
  animals/views.py
  frontend/src/animals/AnimalDetails.js
  frontend/src/animals/AnimalForm.js
  frontend/src/components/ActionsDropdown.js
  frontend/src/dispatch/DispatchSummary.js
  frontend/src/dispatch/VisitNoteForm.js
  frontend/src/hotline/ServiceRequestDetails.js
  frontend/src/shelter/ShelterIntake.js
  frontend/src/vet/DiagnosisForm.js
  frontend/src/vet/ExamForm.js
  frontend/src/vet/MedicalRecordDetails.js
  frontend/src/vet/OrdersForm.js
  frontend/src/vet/TreatmentPlanForm.js
  frontend/src/vet/TreatmentRequestForm.js
  frontend/src/vet/Vet.js
  frontend/src/vet/VetRequestDetails.js
  frontend/src/vet/VetRequestForm.js
  frontend/src/vet/VetRequestSearch.js
  frontend/src/vet/VetStepperWorkflow.js
  frontend/src/vet/components/DiagnosticCard.js
  frontend/src/vet/components/Patient.js
  frontend/src/vet/components/ProcedureCard.js
  frontend/src/vet/components/TreatmentCard.js
  hotline/migrations/0024_auto_20240731_0745.py
  hotline/models.py
  shelter/views.py
  vet/migrations/0008_more_fixtures.py
  vet/views.py
Labels: Good to Merge
